### ISSUE TITLE
Stopped Working?!

### ISSUE THREAD

**Issue by tesarlette** [oodesign/sketch-styler#14] opened 2020-06-25 19:15 UTC
I downloaded the trial, and it was working beautifully for the first 2 days. Now it won't run the "find matching styles" command  at all, regardless of which filter items are selected, and freezes at 25% of the load bar each time. I went ahead and bought the plugin hoping that would remedy the error, but it still won't run even after rebooting everything. 

Trying to hit a hot deadline >_<

**Comment by oodesign** [comment] 2020-06-25 19:43
Hi @tesarlette ,

Sorry to hear that! I'm afraid we're not able to reproduce the issue you describe with our testing set, though.

May I ask...

- Which MacOS, Sketch and SketchStyler versions are you running?
- Is it a standalone file (with local styles), or styles come from linked libraries?
- Even if it's just a local file (with local styles), do you have linked libraries enabled in your Sketch Preferences window?
- And I know this is the toughest one, but by far the most useful one for us --> May you [send us the Sketch file](mailto:oscar@oodesign.me), or a brand new Sketch file with just the texts and styles that are causing the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need the text layers and related text styles.

Also, may you please try to:

- Disable all of your linked libraries (in Sketch Preferences, uncheck all libraries)
- Create a brand new file with some text layers in it (all of them with the same attributes)
- Select a text layer and create a new text style from it (so that it's just assigned to this text layer)
- Try to run the plugin
- Do you get the same issue? Otherwise, does Styler find the text style you just created? If it works and you assign it, does it assign it properly to all other text layers?

Thanks for your help!

**Comment by tesarlette** [comment] 2020-06-25 19:52
Thanks for the quick reply! 
• macOS Catalina version 10.15.5
• it's an enormous sketch file containing a website design, with many pages and artboards, but only about 10 main text styles using Arial and Helvetica
• unfortunately can't share the file as it's client work
• running version of Sketch/Abstract and the plugin for Styler is up to date

**Comment by tesarlette** [comment] 2020-06-25 20:00
update: the plug-in is now working on some of the pages. Seems it is not working on one specific page (with many artboards) that include some screenshots of webpages. This specific page was also copied & pasted from a different master file, so wondering if this is contributing to the issue.

**Comment by oodesign** [comment] 2020-06-25 20:15
Hi @tesarlette ,

Situations where the Sketch file is using styles from an external file that are not available anymore may lead to some issues when using Sketch Styler. Per your description of the issue, it may fit in this scenario. 

We're actively working on a fix for it. Meanwhile, to investigate a bit further your issue, may you please send us the Sketch plugins logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Run the Sketch Styler command you are having issues with.
4. Proceed as usual until you experience the issue you described. Don't quit Sketch yet (this is important, as Sketch logs are deleted when you quit the app).
5. Logs will be stored by this point. May you please [send us your log file](mailto:oscar@oodesign.me) so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by tesarlette** [comment] 2020-06-25 20:39
Interesting, my com.bohemiancoding.sketch3 folder is empty. maybe because the command never fully ran? 
<img width="1180" alt="Screen Shot 2020-06-25 at 4 24 44 PM" src="https://user-images.githubusercontent.com/67438058/85792953-485b9300-b702-11ea-9cbc-9428812244aa.png">
![Screen Shot 2020-06-25 at 4 39 24 PM](https://user-images.githubusercontent.com/67438058/85793056-70e38d00-b702-11ea-872b-625ef28ceba2.png)

**Comment by oodesign** [comment] 2020-06-26 06:39
Hi @tesarlette ,

This is certainly unexpected 😅. We just released v1.5.0, that includes the ability to enable more detailed logs about its processing, and that may help finding the cause of the issue.

May you please update your Styler version (Sketch will prompt you on launch, as usual), enable the logging ability, and send us the tracked logs? You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Sketch Styler logs are disabled by default. You may enable them by going to Plugins > 🏵 Styler > Settings , and switching on the logging ability.
4. Run the Sketch Styler command you were having issues with.
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us your log file](mailto:oscar@oodesign.me) so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment] 2020-07-02 06:08
Hi @tesarlette ,

Are you still experiencing the same issue with Styler?

Thanks!

**Closed as completed** 2020-09-17 14:42 UTC
