### ISSUE TITLE
Nothing happens after "Looking for matching styles" loader.

### ISSUE THREAD

**Issue by VictorienDotNet** [oodesign/sketch-styler#10] opened 2020-03-09 16:56 UTC
When I click on "Find matching styles" button, the loading begin and you mention below : "Looking for matching styles. This may take a minute…". When the loading is finish, I get a blank page. I just can't use this plugin.

My sketch and the plugin seems to b up to date. No update is resquested by both. My Sketch version is Version 63.1

**Comment by oodesign** [comment] 2020-04-28 08:19
Hi @VictorienDotNet ,

I'm so sorry for the late reply! Somehow it got unnoticed. We apologize 😔.

Are you still having this issue with Sketch Styler?

**Comment by VictorienDotNet** [comment] 2020-04-28 15:12
Yes, but it seems that I have this issue with few sketch files. When I use on a new file, the plugin works.

**Comment by oodesign** [comment] 2020-04-28 17:14
Oh, sorry to hear that!

I'm afraid we're not able to reproduce the issue you describe with our testing set, though.

May I ask...

- Which MacOS, Sketch, and Styler version are you using?
- Is it a standalone file (with local styles), or styles come from linked libraries?
- Even if it's just a local file (with local styles), do you have linked libraries enabled in your Sketch Preferences window? If so, disabling them does solve the issue?
- And I know this is the toughest one, but by far the most useful one for us --> May you send us the Sketch file, or a brand new Sketch file with just the texts and styles that are causing the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need the text layers and related text styles.

Thanks a lot for your help!

**Comment by szymonkozlowski** [comment] 2020-04-29 14:11
Hi, I have the same exact problem. Everything is local, without any linked libraries, even in the preferences window. I attach minimal working example in which i could reproduce this behaviour. I've tested it in Sketch 63.1 and 64, on two different machines running MacOS 10.14.6

https://drive.google.com/open?id=1QmJbKTnn5DjppVP7R6RStBIFbYUfvvFJ

**Comment by oodesign** [comment] 2020-04-29 14:30
Hi @szymonkozlowski ,

This is gold! We can actually reproduce the issue, so thank you very much for attaching this file.
I'll make sure to let you know when we find out what the issue is and when we'll be able to release a fix for it.

Meanwhile, may I ask you:
- Do you have "Missing fonts" (missing fonts warning in the top right corner)? If so, does resolving them (replacing them by other fonts) solve the issue?
- Even if you get a blank screen after the loading, if you keep the window open for long time, does it finally show up (may take some minutes)?

**Comment by VictorienDotNet** [comment] 2020-04-29 16:12
From my side, I have :
– macOS Catalina (10.15.3), Sketch 64 and Styler 1.3.12
– It’s a files with four libraries when I deactivate these libraries it’s change anything.
– I have attached an example at his mail 



Thank you :)

**Comment by oodesign** [comment] 2020-04-30 09:35
Hi @VictorienDotNet ,

Thank you for the details. We haven't received the file, though. May you please [send it again](mailto:oscar@oodesign.me)?

Thanks!

**Comment by oodesign** [comment] 2020-05-12 07:47
Hi @VictorienDotNet and @szymonkozlowski,

We just released v1.4.0, that hopefully fixes this issue (and some others).

May you give it a try and let us know how it worked for you?

Thanks a ton! 🥰

**Comment by VictorienDotNet** [comment] 2020-05-30 13:25
Sorry for the late answer, It works :)

**Comment by oodesign** [comment] 2020-05-30 14:08
Glad it works for you!

I'm closing the issue, but please feel free to reopen it (or create a new one) if you have further issues with it.

Thanks!

**Closed as completed by oodesign** 2020-05-30 14:08 UTC
