### ISSUE TITLE
Styler is not applying the styles

### ISSUE THREAD

**Issue by tiagomaricate** [oodesign/sketch-styler#19] opened 2020-11-23 17:10 UTC
After the search, the plugin find many layers without style.
I press to apply the suggested styles and received the message they are replaced.
But when I repeat the process, Styler found the same layers again, without style.
Looks it changes the size, font and color itself, but does not link to the style. So I have the text with the right specs, but without style applied.

**Comment by oodesign** [comment] 2020-11-23 17:31
Hi @tiagomaricate ,

Sorry to hear that :(

May I ask which Sketch Styler, Sketch, and MacOS versions are you using?

To investigate a bit further your issue, may you please send us the Sketch Styler logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Sketch Styler logs are disabled by default. You may enable them by going to Plugins > Sketch Styler > Settings , and switching on the logging ability.
4. Run the Sketch Styler command you were having issues with.
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and reopen the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by tiagomaricate** [comment] 2020-11-23 17:40
> Hi @tiagomaricate ,
> 
> Sorry to hear that :(
> 
> May I ask which Sketch Styler, Sketch, and MacOS versions are you using?
> 
> To investigate a bit further your issue, may you please send us the Sketch Styler logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:
> 
> 1. Quit Sketch
> 2. Open Sketch again, and open the file you're having issues with
> 3. Sketch Styler logs are disabled by default. You may enable them by going to Plugins > Sketch Styler > Settings , and switching on the logging ability.
> 4. Run the Sketch Styler command you were having issues with.
> 5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and reopen the app).
> 6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log
> 
> Thanks a lot for your help! 🥰

I'm using BigSur 11.0.1, Styler idk... I believe is the last version. I just bought and installed it. Sketch is Version 70 (108797).
I'm sent the log to the email you indicated.

**Comment by oodesign** [comment] 2020-11-24 09:26
Hi @tiagomaricate ,

You may find the Sketch Styler version in the plugins list. You may get there by:

- Sketch > Preferences > Plugins
- (or go to) Plugins > Manage plugins

All the installed plugins will show up there, and next to the title and description you may find also the version.

Sketch Styler current version is **v1.5.3**. Is it the one you have?
If it's not, you can get it by:

- Styler does auto-update. If you quit Sketch and open it up again, you should get a notification the top-right corner asking you to update.
- If for some reason that doesn't work for you, you may always find the latest version in https://github.com/oodesign/sketch-styler/releases

**Comment by tiagomaricate** [comment] 2020-11-24 11:33
The version is 1.5.3
I disabled any other plugins to check and the problem persists.
The plugin change the font face, size and color, but don't link the style related to the text layer.

**Comment by oodesign** [comment] 2020-11-24 11:40
Cool! Thanks for checking.

I'm afraid it's an issue that we cannot reproduce with our testing set... 
May I ask you to please [send us](mailto:oscar@oodesign.me) your design file (and related libraries) so that we can investigate it further?

Your files are and will remain confidential. We ensure they will only be used to investigate the issue you're describing, deleted after closing it, and never stored or used for any other means.

Also please feel free to use the sharing platform you prefer to send us the files, if you don't want to send them via email. Just [let us know](mailto:oscar@oodesign.me) the details to get them.

Thank you!

**Closed as completed** 2021-04-15 14:45 UTC
